# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7337c2213f7c9366b5dfd66348f21289"
application_url = "https://shopify-delivery-notifications-kl47y.ondigitalocean.app/"
embedded = true
name = "Custom Delivery Notifications"
handle = "delivery-70"

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "fulfillments/update" ]
  uri = "/webhooks/app/fulfillments-update"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"
  
  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/orders-create"


  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_fulfillments,read_orders,read_products"

[auth]
redirect_urls = [
  "https://shopify-delivery-notifications-kl47y.ondigitalocean.app/auth/callback",
  "https://shopify-delivery-notifications-kl47y.ondigitalocean.app/auth/shopify/callback",
  "https://shopify-delivery-notifications-kl47y.ondigitalocean.app/api/auth/callback"
]

[pos]
embedded = false
